services:
  traefik:
    image: traefik:v2.9
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=easonchaijw@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - simplegrants-backend
      - simplegrants-database
    networks:
      - simplegrants
  simplegrants-backend:
    extends:
      file: ./backend/docker-compose.yml
      service: simplegrants-backend
    env_file:
      - ./backend/.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simplegrants-backend.rule=Host(`api.simplegrants.xyz`)"
      - "traefik.http.routers.simplegrants-backend.tls.certresolver=myresolver"
      - "traefik.http.services.simplegrants-backend.loadbalancer.server.port=3000"
  simplegrants-database:
    extends:
      file: ./backend/docker-compose.yml
      service: simplegrants-database
    env_file:
      - ./backend/.env.production
  simplegrants-frontend:
    container_name: simplegrants-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    restart: on-failure
    env_file:
      - ./frontend/.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.simplegrants-frontend.rule=Host(`simplegrants.xyz`)"
      - "traefik.http.routers.simplegrants-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.simplegrants-frontend.loadbalancer.server.port=3001"
    environment:
      - DEBUG=${DEBUG}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - simplegrants-backend
    networks:
      - simplegrants
volumes:
  simplegrants-frontend:
  simplegrants-backend:
  simplegrants-database:

networks:
  simplegrants:
