services:
  simplegrants-backend:
    extends:
      file: ./backend/docker-compose.dev.yml
      service: simplegrants-backend
    depends_on:
      - simplegrants-database
  simplegrants-database:
    extends:
      file: ./backend/docker-compose.dev.yml
      service: simplegrants-database
  simplegrants-frontend:
    extends:
      file: ./frontend/docker-compose.dev.yml
      service: simplegrants-frontend
    depends_on:
      - simplegrants-backend
volumes:
  simplegrants-database:

networks:
  simplegrants:
