services:
  simplegrants-backend:
    container_name: simplegrants-backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: on-failure
    env_file:
      - .env.production
    ports:
      - 3000:3000
    depends_on:
      - simplegrants-database
    networks:
      - simplegrants
  simplegrants-database:
    container_name: simplegrants-database
    image: postgres:14
    restart: on-failure
    env_file:
      - .env.production
    ports:
      - 5432:5432
    volumes:
      - simplegrants-database:/var/lib/postgresql/data
    networks:
      - simplegrants
volumes:
  simplegrants-database:
networks:
  simplegrants:
